<a href="https://colab.research.google.com/github/umamona/python-turorials/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import  math
#convertion from number to farenheit
farenheit=np.array([0,-20,-5,-15,0])

#formula for conversion if ((Degree F-32)*5/9 =degree C)
celcius=(farenheit-31)*(5/9)
celcius

array([-17.22222222, -28.33333333, -20.        , -25.55555556,
       -17.22222222])

In [5]:
celcius>-20

array([ True, False, False, False,  True])

In [6]:
#modulus operator to numbers in array to see if they are even
celcius%2==0

array([False, False,  True, False, False])