<a href="https://colab.research.google.com/github/umamona/python-turorials/blob/main/slicing%2C_indexing_iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Indexing, Iterating and Slicing
import numpy as np
import math
a=np.array([1,3,5,7])
a[2]

5

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[1,1]

4

In [ ]:
a[1,0]

3

In [ ]:
np.array([a[0,0],a[1,1],a[2,1]])

array([1, 4, 6])

In [ ]:
print(a[[0,1,2],[0,1,1]])

[1 4 6]


In [ ]:
#Boolean Indexing
#here we need to find the element greater than 5 , as like a>5
print(a>5)

[[False False]
 [False False]
 [False  True]]


In [ ]:
print(a>3)

[[False False]
 [False  True]
 [ True  True]]


In [ ]:
print(a[a>5])

[6]


In [ ]:
#slicing
#to create sub array based on the original array
a=np.array([0,1,2,3,4,5])
print(a[:3])

[0 1 2]


In [ ]:
print(a[2:3])

[2]


In [ ]:
print(a[2:4])

[2 3]


In [ ]:
#for multi dimensional array works as same,
a=np.array([[1,2,3,4],[4,5,6,7],[3,5,7,8]])
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 5, 7, 8]])

In [ ]:
print(a)

[[1 2 3 4]
 [4 5 6 7]
 [3 5 7 8]]


In [ ]:
print(a[:2])

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
#if we add another argument to the array, for example a[:2,1:3], we get the first two rows but then the 
#second n third columns values only
a[:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
# replacing the element at position[0,0] is 2 to 500
sub_array=a[:2,1:3]
print("sub_array index[0,0] value before change", sub_array[0,0])
sub_array[0,0]=50
print("sub array index[0,0]value after change",sub_array[0,0])
print("original array index [0,1]value after change:",a[0,1])

sub_array index[0,0] value before change 2
sub array index[0,0]value after change 50
original array index [0,1]value after change: 50


In [ ]:
#trying numpy with datasets
#to load the dataset in numpy we use the genformtxt() function, 



In [51]:
from google.colab import files
 
 
uploaded = files.upload()

Saving winequality-red.csv to winequality-red (1).csv


https://www.geeksforgeeks.org/ways-to-import-csv-files-in-google-colab/

In [71]:
import pandas as pd
import io
 
df = pd.read_csv(io.BytesIO(uploaded['winequality-red.csv']))
print(df)


     fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                                                                                                     
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                

this is numpy program  for dataset use , i got help from 
https://feisky.xyz/machine-learning/library/numpy.html

In [72]:

import numpy as np
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)
wines.shape

(1599, 12)

In [75]:
wines=np.genfromtxt("winequality-red.csv",delimiter=";" , skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [76]:
print("one integer 0 for slicing",wines[:0])

print("0 to 1 for slicing:\n",wines[:,0:1])

one integer 0 for slicing []
0 to 1 for slicing:
 [[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]


In [78]:
wines[:,[0,2,4]]

array([[7.4  , 0.   , 0.076],
       [7.8  , 0.   , 0.098],
       [7.8  , 0.04 , 0.092],
       ...,
       [6.3  , 0.13 , 0.076],
       [5.9  , 0.12 , 0.075],
       [6.   , 0.47 , 0.067]])

In [79]:
#-1 is 
wines[:-1].mean()

7.92617279151022

In [84]:
from google.colab import files
 
 
uploaded = files.upload()

Saving Admission_Predict.csv to Admission_Predict (1).csv


In [86]:
import pandas as pd
import io
 
df = pd.read_csv(io.BytesIO(uploaded['Admission_Predict.csv']))
print(df)


     Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1    

In [88]:

graduate_admission=np.genfromtxt('datasets/Admission_Predict.csv',dtype=None,delimiter=',',skip_header=1,
                                names=('Serial No','GRE Score','TOEFL Score','University Rating','SOP',
                                       'LOR','CGPA','Research','Chance of Admit'))
graduate_admission

OSError: ignored